version: '3.3'


services: 
  app:
    build: ./infra/php
    volumes:
     - ../backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ../backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: line-bot-test
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./infra/DB/volume:/var/lib/mysql
      - ./infra/DB/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 13306:3306


  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 5000:80

  ngrok:
    image: wernight/ngrok
    ports:
      - ${WEB_PORT:-4040}:4040
    environment:
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_PROTOCOL: http
      NGROK_PORT: web:80
